#ifndef _6507_AUTOGENERATED_LABEL_HPP_
#define _6507_AUTOGENERATED_LABEL_HPP_

#include <cstdint>
#include <string>
#include <unordered_map>

class AutoLabel
{
  static uint32_t num_auto_labels;
  static std::unordered_map<uint16_t, AutoLabel> auto_label_map;
  std::string label;

public:
  AutoLabel (void) = default;
};

#endif /* _6507_AUTOGENERATED_LABEL_HPP_ */
